### PR TITLE
updated vendor deps

### PR DESCRIPTION
**Pull request by xh3b4sd**

### CODE REVIEW

**Comment by xh3b4sd** [comment]
Only vendor update. Moving on.

**Comment by fgimenez** [comment]
@xh3b4sd mmm not only vendor, there are also changes related to resources and to the `addFunc`, `deleteFunc` and `updateFunc` pls take a look in case those are not intended

**Comment by fgimenez** [comment]
these are probably required by the new operatorkit, just in case :)

**Comment by xh3b4sd** [comment]
All good. The vendor update required these changes. It is the same as in https://github.com/giantswarm/kvm-operator/pull/177. We tend to not wanting to be blocked by such PRs. In case other unexpected or new changes come along we tend to wait for reviews though. Lets talk if you feel differently. Thanks for raising your voice anyway.

**Pull request merged**
